// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeka3I5wIcNaHStanSyvmnMDY4oKkAG4',
    appId: '1:410551873097:web:613be5bfa5fc3d30e09998',
    messagingSenderId: '410551873097',
    projectId: 'gym-buddy-efa30',
    authDomain: 'gym-buddy-efa30.firebaseapp.com',
    storageBucket: 'gym-buddy-efa30.appspot.com',
    measurementId: 'G-YKX80EM5VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdTv1fUCl9aQ7fD_vjABjE2_BGUnT_p90',
    appId: '1:410551873097:android:5bb5c84005433510e09998',
    messagingSenderId: '410551873097',
    projectId: 'gym-buddy-efa30',
    storageBucket: 'gym-buddy-efa30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQgGbKAsJHZ8jm-dvgnqen4fI5QjSNmM',
    appId: '1:410551873097:ios:c7bf341587de073fe09998',
    messagingSenderId: '410551873097',
    projectId: 'gym-buddy-efa30',
    storageBucket: 'gym-buddy-efa30.appspot.com',
    iosBundleId: 'com.example.gymBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQgGbKAsJHZ8jm-dvgnqen4fI5QjSNmM',
    appId: '1:410551873097:ios:c7bf341587de073fe09998',
    messagingSenderId: '410551873097',
    projectId: 'gym-buddy-efa30',
    storageBucket: 'gym-buddy-efa30.appspot.com',
    iosBundleId: 'com.example.gymBuddy',
  );

}